name: GCP Federation Test
on: [push]

permissions:
  contents: 'read'
  id-token: 'write' # REQUIRED for Federation

jobs:
  test-gcp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to GCP'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/582508909454/locations/global/workloadIdentityPools/wif-pool-github-gcp/providers/github-provider'
          service_account: 'github-wif-test@cms-vpc-control-poc.iam.gserviceaccount.com'

      - name: 'Verify Connection'
        run: |
          gcloud auth list
          gcloud config list
          echo "Connection is Successful!"    

      - name: 'List Buckets'
        run: gcloud storage ls
